<?php

namespace AppBundle\Repository\Writer;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMediaListQueryBuilder($project, $scene){

		$queryBuilder = $this->createQueryBuilder('e')
            ->orderBy('e.id', 'ASC');

        $queryBuilder
            ->leftJoin("e.scene", "s")
            ->leftJoin("s.project", "p")
            ->andWhere('s.project = :project')
            ->setParameter('project', $project);

        if ($scene) {
            $queryBuilder->andWhere('e.scene = :scene')
            ->setParameter('scene', $scene);
        }

        return $queryBuilder;

	}

}
