<?php

namespace AppBundle\Repository\Writer;

/**
 * SceneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SceneRepository extends \Doctrine\ORM\EntityRepository
{
}
