<?php

namespace AppBundle\Repository\Writer;

/**
 * SceneConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SceneConnectionRepository extends \Doctrine\ORM\EntityRepository
{
}
